defaults:
  - _self_

data:
  # CSV for path and metadata to training examples.
  csv_path_train:
  data_path_train:
  csv_path_val:
  data_path_val:
  data_format: h5
  max_len: 2048
  task:
  size:
  sample_mode: normal
  sample_num: 
  tokenizer_path: ./data/tokenizer.json


model:
  use_peft: False
  peft_rank:
  peft_alpha:
  c_s: 1024
  c_hidden: 64
  no_heads: 16
  transition_n: 4
  c_lm_head: 257
  num_blocks_na: 24
  norm_qk: True


    


experiment:
  # Experiment metadata
  name:
  run_id: null
  num_parameters: null

  # Training mode
  use_ddp : True
  use_gpu: True
  num_loader_workers: 1
  prefetch_factor: 10
  use_amp: True

  # Training arguments
  log_freq: 1000
  ckpt_freq: 10000
  batch_size: 64
  num_epoch: 1
  num_steps:
  validate: True

  # Scheduler
  learning_rate: 0.00005
  schedule_type: cosin_decay
  warmup_steps: 10000
  cooldown_steps:
  gamma:
  min_lr_scale:
  period: 259618
  
  # Checkpoint directory to warm start from.
  resume_from_ckpt:
  use_ckpt_conf: False
  warm_start: 
  ckpt_dir: ./ckpt/
  freeze: False

hydra:
  run:
    dir: ./outputs/${experiment.name}/${now:%dD_%mM_%YY_%Hh_%Mm_%Ss}
