defaults:
  - _self_

inference:
  name: moirain_multi
  seed: 123
  nof_samples: 1000

  use_ddp: False

  sample_mode: topp
  temperature: 1.0
  kp: 0.9
  max_len: 50
  num_loader_workers: 1

  output_dir: ./inference_outputs/
  model_path: ./ckpt/moirain_multi/step_21174.pth

data:
  csv_path_test: 
  data_path_test: 
  data_format: csv
  max_len:
  task:
  size:
  sample_mode: normal
  sample_num:
  tokenizer_path: ./data/tokenizer.json
  

hydra:
  run:
    dir: ./outputs/inference/${now:%dD_%mM_%YY_%Hh_%Mm_%Ss}